name: Data Fetching
on: 
  push:
  schedule:
    - cron: "5 19 * * *"
  workflow_dispatch:

jobs:
  Fetch-Route-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.12'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Crawling resources
        run: python waypoints.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: waypoints
          folder: waypoints
          single-commit: true
      - name: Gzip resources
        run: |
          mkdir waypoints_gzip
          for file in waypoints/*.json; do gzip -c "$file" > "waypoints_gzip/$file.gz"; done
      - name: Deploy Gzip
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: waypoints
          folder: waypoints_gzip
          single-commit: true
